import {
  Department,
  Employee,
  Location,
  Item,
  TransactionApproval,
  AuditLogEntry,
  AssetCategory,
  ItemStatus,
  ItemCondition,
  UserRole,
  TransactionType,
  ApprovalStatus,
} from '../types/asset-management';

export const SEED_DEPARTMENTS: Department[] = [
  { id: 'DEP-01', code: 'EXT', nameEn: 'Agricultural Extension Directorate', nameAm: 'የግብርና ኤክስቴንሽን ዳይሬክቶሬት', headEmployeeId: 'EMP-HEAD-01' },
  { id: 'DEP-02', code: 'HORT', nameEn: 'Horticulture Development Directorate', nameAm: 'የሆርቲካልቸር ልማት ዳይሬክቶሬት', headEmployeeId: 'EMP-HEAD-02' },
  { id: 'DEP-03', code: 'PROP', nameEn: 'Procurement & Property Administration', nameAm: 'የግዥና ንብረት አስተዳደር ዳይሬክቶሬት', headEmployeeId: 'EMP-HEAD-03' },
  { id: 'DEP-04', code: 'ICT', nameEn: 'Digital Agriculture & ICT Directorate', nameAm: 'የኢንፎርሜሽን ቴክኖሎጂ ዳይሬክቶሬት', headEmployeeId: 'EMP-HEAD-04' },
  { id: 'DEP-05', code: 'NRM', nameEn: 'Natural Resource Management', nameAm: 'የተፈጥሮ ሀብት አስተዳደር', headEmployeeId: 'EMP-HEAD-05' },
];

export const SEED_LOCATIONS: Location[] = [
  { id: 'LOC-01', siteName: 'MoA Headquarters (Addis Ababa)', building: 'Block B', roomNumber: 'Central Store-01', isCentralStore: true },
  { id: 'LOC-02', siteName: 'MoA Headquarters (Addis Ababa)', building: 'Block A', roomNumber: 'Office 304', isCentralStore: false },
  { id: 'LOC-03', siteName: 'Melkassa Agricultural Research Center', building: 'Machinery Depot', roomNumber: 'Hangar A', isCentralStore: true },
  { id: 'LOC-04', siteName: 'Kulumsa Agricultural Research Center', building: 'Agronomy Building', roomNumber: 'Store 02', isCentralStore: true },
];

export const SEED_EMPLOYEES: Employee[] = [
  // Top Management / Minister
  {
    id: 'EMP-MIN-01',
    payrollId: 'MOA/EXEC-001',
    fullNameEn: 'H.E. Mr. Addisu Arega (Minister)',
    fullNameAm: 'ክቡር አቶ አዲሱ አረጋ (ሚኒስትር)',
    departmentId: 'DEP-03',
    email: 'minister@moa.gov.et',
    phone: '+251911000001',
    role: UserRole.TOP_MANAGEMENT,
  },
  // Department Heads / Approvers
  {
    id: 'EMP-HEAD-01',
    payrollId: 'MOA/DIR-012',
    fullNameEn: 'Tigist Haile (Extension Director)',
    fullNameAm: 'ትዕግስት ኃይሌ (ዳይሬክተር)',
    departmentId: 'DEP-01',
    email: 'tigist.h@moa.gov.et',
    phone: '+251922334455',
    role: UserRole.DEPARTMENT_HEAD,
  },
  {
    id: 'EMP-HEAD-03',
    payrollId: 'MOA/DIR-008',
    fullNameEn: 'Dawit Tadesse (Property Director)',
    fullNameAm: 'ዳዊት ታደሰ (የንብረት ዳይሬክተር)',
    departmentId: 'DEP-03',
    email: 'dawit.t@moa.gov.et',
    phone: '+251933445566',
    role: UserRole.DEPARTMENT_HEAD,
  },
  // Data Encoders (Store Level)
  {
    id: 'EMP-ENC-01',
    payrollId: 'MOA/STORE-102',
    fullNameEn: 'Abebe Bekele (Central Store Encoder)',
    fullNameAm: 'አበበ በቀለ (የመጋዘን ዳታ መዝጋቢ)',
    departmentId: 'DEP-03',
    email: 'abebe.b@moa.gov.et',
    phone: '+251911223344',
    role: UserRole.DATA_ENCODER,
  },
  {
    id: 'EMP-ENC-02',
    payrollId: 'MOA/STORE-105',
    fullNameEn: 'Hiwot Girma (Melkassa Store Encoder)',
    fullNameAm: 'ሕይወት ግርማ (መጋዘን ኃላፊ)',
    departmentId: 'DEP-03',
    email: 'hiwot.g@moa.gov.et',
    phone: '+251944556677',
    role: UserRole.DATA_ENCODER,
  },
  // Field Staff / Custodians
  {
    id: 'EMP-STAFF-01',
    payrollId: 'MOA/EXP-440',
    fullNameEn: 'Kenenisa Gemeda (Senior Agronomist)',
    fullNameAm: 'ቀነኒሳ ገመዳ (አግሮኖሚስት)',
    departmentId: 'DEP-01',
    email: 'kenenisa.g@moa.gov.et',
    phone: '+251955667788',
    role: UserRole.DATA_ENCODER,
  },
];

export const SEED_ITEMS: Item[] = [
  {
    id: 'ITEM-001',
    itemCode: 'MOA-VEH-2024-0001',
    name: 'Toyota Land Cruiser 4WD Field Vehicle',
    category: AssetCategory.VEHICLE,
    serialNumber: 'TOY-LC-8839201',
    unitCostETB: 12500000,
    status: ItemStatus.ISSUED,
    condition: ItemCondition.GOOD,
    storeLocationId: 'LOC-01',
    currentCustodianId: 'EMP-STAFF-01',
    assignedDepartmentId: 'DEP-01',
    ifmisSlipNumber: 'IFMIS-GRN-2024-0419',
    ifmisSlipDateGc: '2024-02-10',
    ifmisSlipDateEc: '2016-06-02',
    registeredById: 'EMP-ENC-01',
    approvedById: 'EMP-HEAD-03',
    createdAtGc: '2024-02-10',
    createdAtEc: '2016-06-02',
    history: [
      {
        id: 'HIST-001',
        dateGc: '2024-02-10',
        dateEc: '2016-06-02',
        action: 'STOCK_IN_APPROVED',
        fromEntity: 'IFMIS Slip IFMIS-GRN-2024-0419',
        toEntity: 'Central Store-01',
        performedBy: 'Abebe Bekele',
        performedByRole: UserRole.DATA_ENCODER,
        approvedBy: 'Dawit Tadesse',
        ifmisSlipNumber: 'IFMIS-GRN-2024-0419',
        notes: 'Inbound delivery verified and approved',
      },
      {
        id: 'HIST-002',
        dateGc: '2024-02-15',
        dateEc: '2016-06-07',
        action: 'STOCK_OUT_APPROVED',
        fromEntity: 'Central Store-01',
        toEntity: 'Kenenisa Gemeda (Agricultural Extension)',
        performedBy: 'Abebe Bekele',
        performedByRole: UserRole.DATA_ENCODER,
        approvedBy: 'Tigist Haile',
        ifmisSlipNumber: 'IFMIS-SIV-2024-0105',
        notes: 'Assigned for regional farmer extension program',
      },
    ],
  },
  {
    id: 'ITEM-002',
    itemCode: 'MOA-AGR-2024-0002',
    name: 'Massey Ferguson MF-385 Tractor 85HP',
    category: AssetCategory.AGRI_MACHINERY,
    serialNumber: 'MF-385-99201',
    unitCostETB: 4800000,
    status: ItemStatus.AVAILABLE,
    condition: ItemCondition.NEW,
    storeLocationId: 'LOC-03',
    currentCustodianId: null,
    assignedDepartmentId: null,
    ifmisSlipNumber: 'IFMIS-GRN-2024-0580',
    ifmisSlipDateGc: '2024-03-01',
    ifmisSlipDateEc: '2016-06-22',
    registeredById: 'EMP-ENC-02',
    approvedById: 'EMP-HEAD-03',
    createdAtGc: '2024-03-01',
    createdAtEc: '2016-06-22',
    history: [
      {
        id: 'HIST-003',
        dateGc: '2024-03-01',
        dateEc: '2016-06-22',
        action: 'STOCK_IN_APPROVED',
        fromEntity: 'IFMIS Slip IFMIS-GRN-2024-0580',
        toEntity: 'Melkassa Machinery Depot',
        performedBy: 'Hiwot Girma',
        performedByRole: UserRole.DATA_ENCODER,
        approvedBy: 'Dawit Tadesse',
        ifmisSlipNumber: 'IFMIS-GRN-2024-0580',
        notes: 'Delivered under National Mechanization Project',
      },
    ],
  },
  {
    id: 'ITEM-003',
    itemCode: 'MOA-IT-2024-0003',
    name: 'Dell PowerEdge R750 Rack Server',
    category: AssetCategory.IT_EQUIPMENT,
    serialNumber: 'DELL-R750-84729',
    unitCostETB: 850000,
    status: ItemStatus.AVAILABLE,
    condition: ItemCondition.NEW,
    storeLocationId: 'LOC-01',
    currentCustodianId: null,
    assignedDepartmentId: null,
    ifmisSlipNumber: 'IFMIS-GRN-2024-0612',
    ifmisSlipDateGc: '2024-04-12',
    ifmisSlipDateEc: '2016-08-04',
    registeredById: 'EMP-ENC-01',
    approvedById: 'EMP-HEAD-03',
    createdAtGc: '2024-04-12',
    createdAtEc: '2016-08-04',
    history: [
      {
        id: 'HIST-004',
        dateGc: '2024-04-12',
        dateEc: '2016-08-04',
        action: 'STOCK_IN_APPROVED',
        fromEntity: 'IFMIS Slip IFMIS-GRN-2024-0612',
        toEntity: 'Central Store-01',
        performedBy: 'Abebe Bekele',
        performedByRole: UserRole.DATA_ENCODER,
        approvedBy: 'Dawit Tadesse',
        ifmisSlipNumber: 'IFMIS-GRN-2024-0612',
        notes: 'Received for MoA Data Center expansion',
      },
    ],
  },
  // Item pending Stock In approval
  {
    id: 'ITEM-004',
    itemCode: 'MOA-LAB-2024-0004',
    name: 'Digital Soil Nitrogen & Phosphorus Spectrophotometer',
    category: AssetCategory.LAB_EQUIPMENT,
    serialNumber: 'SPEC-NPK-3341',
    unitCostETB: 1450000,
    status: ItemStatus.PENDING_STOCK_IN,
    condition: ItemCondition.NEW,
    storeLocationId: 'LOC-01',
    currentCustodianId: null,
    assignedDepartmentId: null,
    ifmisSlipNumber: 'IFMIS-GRN-2024-0899',
    ifmisSlipDateGc: '2024-09-18',
    ifmisSlipDateEc: '2017-01-08',
    registeredById: 'EMP-ENC-01',
    createdAtGc: '2024-09-18',
    createdAtEc: '2017-01-08',
    history: [
      {
        id: 'HIST-005',
        dateGc: '2024-09-18',
        dateEc: '2017-01-08',
        action: 'STOCK_IN_REGISTERED',
        fromEntity: 'IFMIS Slip IFMIS-GRN-2024-0899',
        toEntity: 'Pending Central Store Approval',
        performedBy: 'Abebe Bekele',
        performedByRole: UserRole.DATA_ENCODER,
        ifmisSlipNumber: 'IFMIS-GRN-2024-0899',
        notes: 'Submitted by Data Encoder; awaiting Department Head sign-off',
      },
    ],
  },
  // Item pending Stock Out approval
  {
    id: 'ITEM-005',
    itemCode: 'MOA-IT-2024-0005',
    name: 'HP EliteBook 840 G10 Core i7 Laptops (Lot 5)',
    category: AssetCategory.IT_EQUIPMENT,
    serialNumber: 'HP-EB-109283-05',
    unitCostETB: 420000,
    status: ItemStatus.PENDING_STOCK_OUT,
    condition: ItemCondition.NEW,
    storeLocationId: 'LOC-01',
    currentCustodianId: null,
    assignedDepartmentId: 'DEP-01',
    ifmisSlipNumber: 'IFMIS-GRN-2024-0710',
    ifmisSlipDateGc: '2024-05-15',
    ifmisSlipDateEc: '2016-09-07',
    registeredById: 'EMP-ENC-01',
    approvedById: 'EMP-HEAD-03',
    createdAtGc: '2024-05-15',
    createdAtEc: '2016-09-07',
    history: [
      {
        id: 'HIST-006',
        dateGc: '2024-05-15',
        dateEc: '2016-09-07',
        action: 'STOCK_IN_APPROVED',
        fromEntity: 'IFMIS Slip IFMIS-GRN-2024-0710',
        toEntity: 'Central Store-01',
        performedBy: 'Abebe Bekele',
        performedByRole: UserRole.DATA_ENCODER,
        approvedBy: 'Dawit Tadesse',
        ifmisSlipNumber: 'IFMIS-GRN-2024-0710',
      },
      {
        id: 'HIST-007',
        dateGc: '2024-09-22',
        dateEc: '2017-01-12',
        action: 'STOCK_OUT_REQUESTED',
        fromEntity: 'Central Store-01',
        toEntity: 'Tigist Haile (Agricultural Extension)',
        performedBy: 'Abebe Bekele',
        performedByRole: UserRole.DATA_ENCODER,
        ifmisSlipNumber: 'IFMIS-SIV-2024-0320',
        notes: 'Requested for national soil fertility mapping task force',
      },
    ],
  },
];

export const SEED_APPROVALS: TransactionApproval[] = [
  {
    id: 'APPR-001',
    transactionType: TransactionType.STOCK_IN,
    itemId: 'ITEM-004',
    itemCode: 'MOA-LAB-2024-0004',
    itemName: 'Digital Soil Nitrogen & Phosphorus Spectrophotometer',
    ifmisSlipNumber: 'IFMIS-GRN-2024-0899',
    ifmisSlipDateGc: '2024-09-18',
    ifmisSlipDateEc: '2017-01-08',
    requestedById: 'EMP-ENC-01',
    purposeOrRemarks: 'Supplier delivery under FAO Grant Agreement; delivery slip inspected.',
    status: ApprovalStatus.PENDING,
    currentStage: 1,
    createdAtGc: '2024-09-18',
    createdAtEc: '2017-01-08',
  },
  {
    id: 'APPR-002',
    transactionType: TransactionType.STOCK_OUT,
    itemId: 'ITEM-005',
    itemCode: 'MOA-IT-2024-0005',
    itemName: 'HP EliteBook 840 G10 Core i7 Laptops (Lot 5)',
    ifmisSlipNumber: 'IFMIS-SIV-2024-0320',
    ifmisSlipDateGc: '2024-09-22',
    ifmisSlipDateEc: '2017-01-12',
    requestedById: 'EMP-ENC-01',
    recipientEmployeeId: 'EMP-HEAD-01',
    targetDepartmentId: 'DEP-01',
    purposeOrRemarks: 'Requisition for National Soil Fertility Task Force team.',
    status: ApprovalStatus.PENDING,
    currentStage: 1,
    createdAtGc: '2024-09-22',
    createdAtEc: '2017-01-12',
  },
];

export const SEED_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-001',
    timestampGc: '2024-02-10 09:30:00',
    timestampEc: '2016-06-02 03:30',
    userId: 'EMP-ENC-01',
    userName: 'Abebe Bekele',
    userRole: UserRole.DATA_ENCODER,
    action: 'REGISTER_STOCK_IN',
    entityType: 'ITEM',
    entityId: 'ITEM-001',
    ifmisSlipNumber: 'IFMIS-GRN-2024-0419',
    details: 'Registered Toyota Land Cruiser via IFMIS slip IFMIS-GRN-2024-0419',
  },
  {
    id: 'AUD-002',
    timestampGc: '2024-02-10 14:15:00',
    timestampEc: '2016-06-02 08:15',
    userId: 'EMP-HEAD-03',
    userName: 'Dawit Tadesse',
    userRole: UserRole.DEPARTMENT_HEAD,
    action: 'APPROVE_STOCK_IN',
    entityType: 'APPROVAL',
    entityId: 'ITEM-001',
    ifmisSlipNumber: 'IFMIS-GRN-2024-0419',
    details: 'Approved stock-in for Toyota Land Cruiser. Status changed to AVAILABLE in Central Store.',
  },
  {
    id: 'AUD-003',
    timestampGc: '2024-02-15 11:00:00',
    timestampEc: '2016-06-07 05:00',
    userId: 'EMP-HEAD-01',
    userName: 'Tigist Haile',
    userRole: UserRole.DEPARTMENT_HEAD,
    action: 'APPROVE_STOCK_OUT',
    entityType: 'STOCK_OUT',
    entityId: 'ITEM-001',
    ifmisSlipNumber: 'IFMIS-SIV-2024-0105',
    details: 'Approved stock-out to Kenenisa Gemeda. Item status updated to ISSUED.',
  },
  {
    id: 'AUD-004',
    timestampGc: '2024-09-18 10:20:00',
    timestampEc: '2017-01-08 04:20',
    userId: 'EMP-ENC-01',
    userName: 'Abebe Bekele',
    userRole: UserRole.DATA_ENCODER,
    action: 'REGISTER_STOCK_IN',
    entityType: 'STOCK_IN',
    entityId: 'ITEM-004',
    ifmisSlipNumber: 'IFMIS-GRN-2024-0899',
    details: 'Registered Soil Spectrophotometer. Waiting for Department Head approval.',
  },
];
